/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.jdialogs;

import UI.src.ui.utils.AnimalTableModel;
import UI.src.ui.utils.ServTableModel;
import UI.src.ui.utils.Util;
import models.Animal;
import models.Contrato;
import models.Proveedor;
import services.AnimalService;
import services.ContratoService;
import services.ServicioService;
import utils.Utils;

import javax.swing.*;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.*;

/**
 *
 * @author pc8
 */
public class CrearContrato extends javax.swing.JDialog {
    
    private Date fechaInic;
    private Date fechaFin;
    private Date fechaConc;
    private Proveedor proveedor = null;
    private List<HashMap<String, String>> lista;
    private ServTableModel tableModel;
    
    public CrearContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        lista = new ArrayList<>();
        initComponents();
        tableModel = new ServTableModel();
        llenarTabla();
        servTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        fechaInicTxt = new javax.swing.JTextField();
        InicioBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaFinTxt = new javax.swing.JTextField();
        finBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fechaConcTxt = new javax.swing.JTextField();
        concBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        servTable = new javax.swing.JTable();
        aggBtn = new javax.swing.JButton();
        borrBtn = new javax.swing.JButton();
        provTxt = new javax.swing.JTextField();
        InicioBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Fecha Inicio:");

        fechaInicTxt.setFocusable(false);
        fechaInicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaInicTxtActionPerformed(evt);
            }
        });

        InicioBtn.setText("Seleccionar");
        InicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo Servicio:");

        jLabel5.setText("Fecha Fin:");

        fechaFinTxt.setFocusable(false);
        fechaFinTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFinTxtActionPerformed(evt);
            }
        });

        finBtn.setText("Seleccionar");
        finBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha Conciliación:");

        fechaConcTxt.setFocusable(false);
        fechaConcTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaConcTxtActionPerformed(evt);
            }
        });

        concBtn.setText("Seleccionar");
        concBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concBtnActionPerformed(evt);
            }
        });

        descrArea.setColumns(20);
        descrArea.setLineWrap(true);
        descrArea.setRows(5);
        jScrollPane1.setViewportView(descrArea);

        jLabel7.setText("Proveedor:");

        aceptarBtn.setBackground(new java.awt.Color(51, 51, 255));
        aceptarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setBackground(new java.awt.Color(51, 51, 255));
        cancelarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Servicios");

        servTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(servTable);

        aggBtn.setText("Agregar");
        aggBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggBtnActionPerformed(evt);
            }
        });

        borrBtn.setText("Borrar");
        borrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrBtnActionPerformed(evt);
            }
        });

        provTxt.setFocusable(false);
        provTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provTxtActionPerformed(evt);
            }
        });

        InicioBtn1.setText("Seleccionar");
        InicioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechaFinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(finBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechaInicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(InicioBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(provTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InicioBtn1))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fechaConcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(concBtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)
                                .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aggBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InicioBtn1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaInicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InicioBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaFinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(finBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaConcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(concBtn)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aggBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaInicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaInicTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicTxtActionPerformed

    private void InicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelctFecha dialog = new SelctFecha(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
                fechaInic = dialog.getFecha();
                if(fechaInic != null)
                fechaInicTxt.setText(Util.formatFecha(fechaInic));
            }
        });
    }//GEN-LAST:event_InicioBtnActionPerformed

    private void fechaFinTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFinTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinTxtActionPerformed

    private void finBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelctFecha dialog = new SelctFecha(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
                fechaFin = dialog.getFecha();
                if(fechaFin != null)
                    fechaFinTxt.setText(Util.formatFecha(fechaFin));
            }
        });
    }//GEN-LAST:event_finBtnActionPerformed

    private void fechaConcTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaConcTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaConcTxtActionPerformed

    private void concBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelctFecha dialog = new SelctFecha(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
                fechaConc = dialog.getFecha();
                if(fechaConc != null)
                    fechaConcTxt.setText(Util.formatFecha(fechaConc));
            }
        });
    }//GEN-LAST:event_concBtnActionPerformed

    private void llenarTabla(){
        limpiarTabla();
        for (HashMap<String, String> map: lista) {
            tableModel.agregarServ(map.get("precio"),map.get("recarga") , map.get("duracion"), map.get("descrip"));
        }
    }

    private void limpiarTabla(){
        int cantFil = tableModel.getRowCount()-1;
        for(int i=cantFil ; i>=0 ; i--){
            tableModel.removeRow(i);
        }
    }

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        try {
            validarCampos();
            String descripc = descrArea.getText().trim();

            Contrato contrato = ContratoService.createContrato(proveedor.proveedor_id(), Util.convertirFecha(fechaInic), Util.convertirFecha(fechaFin), Util.convertirFecha(fechaConc), descripc);

            for (HashMap<String, String> map: lista) {
                double precioBase = Double.parseDouble(map.get("precio"));
                double recargo = Double.parseDouble(map.get("recarga"));
                int duracion = Integer.parseInt(map.get("duracion"));
                String descrip = map.get("descrip");
                
                ServicioService.createServicio(contrato.contratoId(), contrato.proveedorId(), precioBase, recargo, duracion, descrip);
            }
            
            this.hide();
            JOptionPane.showMessageDialog(null, "Creado Correctamente", "Creado Satisfactoriamente", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException e1){
            String mensajeError = "Error de base de datos: ";
            if (e1.getMessage().contains("El proveedor ya tiene un contrato activo"))
                mensajeError += "El proveedor ya tiene un contrato activo";
            JOptionPane.showMessageDialog(null, mensajeError, "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            e1.printStackTrace();
        }
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void aggBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ui.jdialogs.CrearServicio dialog = new CrearServicio(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
                HashMap<String, String> mapeo = dialog.getMap();
                System.out.println(mapeo);
                if (mapeo != null){
                    lista.add(mapeo);
                    llenarTabla();
                }
            }
        });
    }//GEN-LAST:event_aggBtnActionPerformed

    private void borrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrBtnActionPerformed
        dispose();
    }//GEN-LAST:event_borrBtnActionPerformed

    private void provTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provTxtActionPerformed

    private void InicioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBtn1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ui.jdialogs.SelectProv dialog = new SelectProv(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
                Proveedor prov = dialog.getProveedor();
                if(prov != null){
                    proveedor = prov;
                    provTxt.setText(proveedor.nombre_proveedor());
                }
            }
        });
    }//GEN-LAST:event_InicioBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    public boolean validarCampos() {
        try {
            if(provTxt.getText().isEmpty() || fechaConcTxt.getText().isEmpty() || fechaFinTxt.getText().isEmpty()
            || fechaInicTxt.getText().isEmpty() || descrArea.getText().trim().isEmpty())
                throw new IllegalArgumentException("Todos los campos son obligatorios");
            if (servTable.getRowCount() == 0)
                throw new IllegalArgumentException("El Contrato tiene que aunque sea tener un servicio");
            if (fechaInic.after(fechaFin) || fechaInic.after(fechaConc))
                throw new IllegalArgumentException("La fecha de inicio no puede ser despues de la fecha fin o la fecha de conciiación");
            if (fechaConc.after(fechaFin))
                throw new IllegalArgumentException("La fecha de conciliación no puede ser despues de la de fin");
            if (fechaInic.before(new Date()))
                throw new IllegalArgumentException("Las fechas no pueden ser antes de la actual");
            
            int diasMax = 0;
            for (HashMap<String, String> map: lista) {
                int dias = Integer.parseInt(map.get("duracion"));
                if(diasMax < dias)
                    diasMax = dias;
            }

            LocalDate fechaInicLocal = fechaInic.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFinLocal = fechaFin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            long dias = ChronoUnit.DAYS.between(fechaInicLocal, fechaFinLocal);

            System.out.println(diasMax + " " + dias);
            
            if (diasMax > dias)
                throw new IllegalArgumentException("Los dias de duración de los servicios no pueden ser mayor que los dias de duracion del contrato");

            return true;

        } catch (IllegalArgumentException e) {
            throw e;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InicioBtn;
    private javax.swing.JButton InicioBtn1;
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton aggBtn;
    private javax.swing.JButton borrBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton concBtn;
    private javax.swing.JTextArea descrArea;
    private javax.swing.JTextField fechaConcTxt;
    private javax.swing.JTextField fechaFinTxt;
    private javax.swing.JTextField fechaInicTxt;
    private javax.swing.JButton finBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField provTxt;
    private javax.swing.JTable servTable;
    // End of variables declaration//GEN-END:variables
}
